//Map
//Map is a collection of key and value pair
//Map is not implementation or extension of Collection interface.Map is itself interface in Collection API
//HashMap is a class which implements Map
//We also have HashTable .The difference between HashTable and HashMap is synchronization.HashTable is synchronized(If multiple threads are working better to use HashTable)
/*package COLLECTIONS;


import java.util.Map;
import java.util.HashMap;

public class Demo3 {
    public static void main(String a[]){
        //Parameters: the type of keys maintained by this map ,the type of mapped values
        //since collection API uses only objects we use String and Integer object
        Map<String,Integer>Students = new HashMap<>();
            Students.put("Harika",99);
            Students.put("Santhu",96);
            Students.put("Harsh",97);
            Students.put("Navin",92);
            //put says try to add the elements in map .If you already have this key replace the value
            Students.put("Santhu", 100); //now value of Santhu is updated to 100
            //generally map doesnot have duplicate keys

            System.out.println(Students); //we can directly print object
            //In HashMap, elements are stored based on the hash code of the keys, not in the order you added them.
            //{Navin=92, Harsh=97, Santhu=100, Harika=99} //hash code is generated by computer for manual checking we can have lexicographically arrangement(sometime not always)

            System.out.println(Students.keySet());//prints only keys
            //[Navin, Harsh, Santhu, Harika]

            System.out.println(Students.values()); //prints only values
            //[92, 97, 100, 99]

            System.out.println(Students.get("Harsh")); //gives value of "Harsh" key //97

            for(String key: Students.keySet()){
                System.out.println(key + " : " + Students.get(key));
            }
            //O/P:
            // Navin : 92
            // Harsh : 97
            // Santhu : 100
            // Harika : 99
    }
}*/

//To preserve the order we use LinkedHashMap
package COLLECTIONS;


import java.util.Map;
import java.util.LinkedHashMap;

public class Demo3 {
    public static void main(String a[]){
        //Parameters: the type of keys maintained by this map ,the type of mapped values
        //since collection API uses only objects we use String and Integer object
        Map<String,Integer>Students = new LinkedHashMap<>();
            Students.put("Harika",99);
            Students.put("Santhu",96);
            Students.put("Harsh",97);
            Students.put("Navin",92);
            //put says try to add the elements in map .If you already have this key replace the value
            Students.put("Santhu", 100); //now value of Santhu is updated to 100
            //generally map doesnot have duplicate keys

            System.out.println(Students); //we can directly print object
            //In HashMap, elements are stored based on the hash code of the keys, not in the order you added them.
            //{Harika=99, Santhu=100, Harsh=97, Navin=92}

            System.out.println(Students.keySet());//prints only keys
            //[Harika, Santhu, Harsh, Navin]

            System.out.println(Students.values()); //prints only values
            //[99, 100, 97, 92]

            System.out.println(Students.get("Harsh")); //gives value of "Harsh" key //97

            for(String key: Students.keySet()){
                System.out.println(key + " : " + Students.get(key));
            }
            //O/P:
            // Harika : 99
            // Santhu : 100
            // Harsh : 97
            // Navin : 92
    }
}
